### ISSUE TITLE
How do I use this with PhantomJS/Poltergeist?

### ISSUE THREAD

**Issue by ghost** [wrozka/capybara-angular#1]
Im using poltergeist as my JS driver for Capybara. I installed this gem but didnt notice anything different. Im still getting race errors where Capybara moves on before all Angular AJAX requests are completed.

**Comment by c-ro** [comment]
@thoughtpunch @tirdadc -- either of you figure out how to get this working?

**Comment by tirdadc** [comment]
@c-ro no, and since then I've pretty much moved on to mostly React rather than Angular.

I do however remember solving a lot of race condition issues with Capybara testing that involved Javascript by following the sort of advice presented [in this blog post](https://robots.thoughtbot.com/write-reliable-asynchronous-integration-tests-with-capybara).
