### ISSUE TITLE
Request for Assistance: Understanding the Gap

### ISSUE THREAD

**Issue by pivotaljohn** [wrozka/capybara-angular#21]
Sorry, folks, for submitting this as an issue — I couldn't find an email address to which I would send this inquiry.

I'm trying to understand the functionality gap in Capybara that this gem addresses.  From what I can tell, reading through Capybara::Node::Base#synchronize, as long as an expectation is not met, it will retry up to some *maximum* timeout. This means that if an expectation has not yet been met, regardless of the delay, Capybara "waits." (really, it retries)...

So, how does the situation improve by specifically querying Angular for its internal state?  I suspect I'm missing something important yet subtle.

Thanks!

**Comment by wrozka** [comment]
Hi John, no worries, let me explain it here.

As you wrote, Capybara waits for the maximum timeout until the expectation fails, but some operation may take longer. By looking into the angular state (via the API exposed for the test purposes) capybara can wait as much as it is needed.

**Comment by psyho** [comment]
You are right the difference is subtle: Capybara waits for something to happen on a page (an element to appear/disappear, etc.). If this does not happen withing some timeout, the test fails.

By hooking into Angular internals, we make capybara wait for Angular to finish processing the page. Once things are stable, it's safe to make assertions about the page. This way there's no guesswork - if there is nothing going on in the background, and the assertion fails, that's because of a bug. Without that knowledge, you can not be sure if it's a real bug, or if it's a XHR request that's taking longer than usual due to high load on the CI server or similar.

This means that you can set a pretty high timeout value - it will only be reached if the page continues working for a very long time, which almost never happens. With plain Capybara you can't do that, because every failed test will be extended by that timeout.

**Comment by pivotaljohn** [comment]
Brilliant; I absolutely appreciate the value of quick running tests, so this resonates with me.

Thanks for taking the time to explain.

Cheers!
